---
name: Build Docker Image

on:
  push:
    paths:
      - Dockerfile
      - VERSION
    tags:
      - '![0-9].*'
      - "**"

  pull_request:
    paths:
      - Dockerfile
      - VERSION
    tags:
      - '![0-9].*'
      - "**"

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Grab the version to use.
        id: v1
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Grab the timestamp to use.
        id: v2
        run: echo "timestamp=$(cat GITHUB_SHA:0:12)" >> $GITHUB_OUTPUT

      - name: Build the Docker image.
        uses: docker/build-push-action@v3
        with:
          build-args: |
            VERSION=${{ steps.v1.outputs.version }}
          tags: dcjulian29/bind:${{ steps.v1.outputs.version }}-${{ steps.v2.outputs.timestamp }}
